"""yfinance daily OHLCV download with caching and fail-loud quality gates.

Prices are the ONLY price source for the VOL campaign (pre-registration).
Download window: 2022-01-01 through 2026-07-15 inclusive. The cache file
``data/vol_prices.parquet`` is deliberately NOT committed (large); it is
regenerated by ``run_campaign.py build-frame``.

Download gaps are logged explicitly (per ticker, per missing date) and
never backfilled. Fail-loud gates (DataQualityError):
- duplicate (ticker, date) rows
- timestamp ordering violations within a ticker
- NaN closes anywhere in the panel
- zero-volume stretches (>= 3 consecutive union-calendar days with
  volume == 0) inconsistent with the exchange calendar
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from signal_lab.vol import universe

PRICE_START = "2022-01-01"
PRICE_END_EXCLUSIVE = "2026-07-16"  # yfinance end is exclusive; last bar 2026-07-15

PRICE_COLUMNS = ["ticker", "date", "open", "high", "low", "close", "adj_close", "volume"]

ZERO_VOLUME_STRETCH_DAYS = 3


class DataQualityError(ValueError):
    """Raised when a price data-quality gate fails loudly."""


def _batch_download(tickers: list[str], start: str, end: str) -> pd.DataFrame:
    """Download one batch via yfinance; returns long-format OHLCV."""
    import yfinance as yf

    yq = [universe.yfinance_ticker(t) for t in tickers]
    raw = yf.download(
        yq,
        start=start,
        end=end,
        auto_adjust=False,
        progress=False,
        threads=True,
    )
    if raw is None or len(raw) == 0:
        raise DataQualityError(f"yfinance returned no rows for batch of {len(tickers)} tickers")
    # yfinance 1.7: columns are MultiIndex (field, ticker) for multi-ticker
    # downloads. Normalize both orientations defensively.
    frames = []
    if isinstance(raw.columns, pd.MultiIndex):
        lvl0 = [str(c) for c in raw.columns.get_level_values(0)]
        if set(lvl0) & {"Open", "High", "Low", "Close", "Adj Close", "Volume"}:
            ticker_lvl = 1
        else:
            ticker_lvl = 0
        for canon, yq_t in zip(tickers, yq):
            # select by ticker level explicitly
            sel = raw.xs(yq_t, axis=1, level=ticker_lvl)
            frames.append(_normalize_batch_frame(sel, canon))
    else:
        if len(tickers) != 1:
            raise DataQualityError("single-level columns with multiple tickers")
        frames.append(_normalize_batch_frame(raw, tickers[0]))
    return pd.concat(frames, ignore_index=True)


def _normalize_batch_frame(df: pd.DataFrame, canonical: str) -> pd.DataFrame:
    cols = {str(c): c for c in df.columns}
    def pick(*names):
        for n in names:
            if n in cols:
                return df[cols[n]]
        raise DataQualityError(f"missing OHLCV field for {canonical}: {names}")
    out = pd.DataFrame({
        "ticker": canonical,
        "date": pd.to_datetime(df.index).tz_convert(None).normalize()
        if getattr(df.index, "tz", None) is not None
        else pd.to_datetime(df.index).normalize(),
        "open": pd.to_numeric(pick("Open"), errors="coerce"),
        "high": pd.to_numeric(pick("High"), errors="coerce"),
        "low": pd.to_numeric(pick("Low"), errors="coerce"),
        "close": pd.to_numeric(pick("Close"), errors="coerce"),
        "adj_close": pd.to_numeric(pick("Adj Close", "AdjClose"), errors="coerce"),
        "volume": pd.to_numeric(pick("Volume"), errors="coerce"),
    })
    return out[PRICE_COLUMNS]


def download_prices(
    tickers: list[str] | None = None,
    start: str = PRICE_START,
    end: str = PRICE_END_EXCLUSIVE,
    batch_size: int = 30,
    log=print,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Download daily OHLCV for the universe.

    Returns (prices, gaps): prices is the long panel; gaps lists
    (ticker, missing_date) for union-calendar days absent from a ticker's
    bars. Gaps are logged explicitly and never backfilled.
    """
    tickers = tickers or universe.universe_tickers()
    batches = [tickers[i:i + batch_size] for i in range(0, len(tickers), batch_size)]
    frames = []
    for i, batch in enumerate(batches):
        log(f"[prices] batch {i + 1}/{len(batches)}: {len(batch)} tickers")
        frames.append(_batch_download(batch, start, end))
    prices = pd.concat(frames, ignore_index=True)
    prices = prices.sort_values(["ticker", "date"]).reset_index(drop=True)
    prices = trim_prelisting_history(prices, log=log)

    calendar = np.sort(prices["date"].unique())
    gap_rows = []
    for t, grp in prices.groupby("ticker"):
        have = set(grp["date"])
        for d in calendar:
            if d not in have:
                gap_rows.append({"ticker": t, "missing_date": pd.Timestamp(d).date().isoformat()})
    gaps = pd.DataFrame(gap_rows, columns=["ticker", "missing_date"])
    if len(gaps):
        log(f"[prices] {len(gaps)} ticker-day gaps across "
            f"{gaps['ticker'].nunique()} tickers (logged, not filled)")
    else:
        log("[prices] no download gaps")
    return prices, gaps


def trim_prelisting_history(prices: pd.DataFrame, log=print) -> pd.DataFrame:
    """Drop each ticker's leading all-NaN-close prefix (pre-listing days).

    Spinoffs (GEV listed 2024-04, SNDK 2025-02) did not trade before
    listing; yfinance returns NaN rows for those dates. Dropping the
    prefix is explicit and logged, not backfilling. NaN closes anywhere
    at/after a ticker's first traded day still fail loudly in
    ``validate_prices``.
    """
    kept = []
    for t, grp in prices.sort_values(["ticker", "date"]).groupby("ticker"):
        grp = grp.reset_index(drop=True)
        first = int(grp["close"].notna().to_numpy().argmax())
        if grp["close"].isna().all():
            raise DataQualityError(f"ticker {t} has no valid closes at all")
        if first > 0:
            log(f"[prices] {t}: dropping {first} pre-listing NaN days "
                f"(first trade {grp.loc[first, 'date'].date().isoformat()})")
        kept.append(grp.iloc[first:])
    return pd.concat(kept, ignore_index=True)


def validate_prices(prices: pd.DataFrame, log=print) -> pd.DataFrame:
    """Fail-loud data-quality gates. Returns the panel unchanged."""
    missing = [c for c in PRICE_COLUMNS if c not in prices.columns]
    if missing:
        raise DataQualityError(f"price panel missing columns: {missing}")

    dup = prices.duplicated(subset=["ticker", "date"]).sum()
    if dup:
        bad = prices[prices.duplicated(subset=["ticker", "date"], keep=False)]
        raise DataQualityError(
            f"{dup} duplicate (ticker, date) rows, e.g. "
            f"{bad[['ticker', 'date']].head(3).to_dict('records')}"
        )

    for t, grp in prices.groupby("ticker"):
        d = grp["date"].to_numpy()
        if not (np.diff(d.astype("datetime64[D]").astype(np.int64)) > 0).all():
            raise DataQualityError(f"timestamp ordering violation for {t}")

    n_nan_close = int(prices["close"].isna().sum())
    if n_nan_close:
        bad = prices[prices["close"].isna()][["ticker", "date"]].head(5)
        raise DataQualityError(
            f"{n_nan_close} NaN closes; e.g. {bad.to_dict('records')}"
        )

    # Zero-volume stretches inconsistent with the exchange calendar: the
    # union calendar says the exchange was open, so a multi-day run of
    # explicit zero volume is corrupt data, not a quiet market.
    calendar = np.sort(prices["date"].unique())
    cal_set = set(pd.DatetimeIndex(calendar).normalize())
    problems = []
    for t, grp in prices.groupby("ticker"):
        g = grp.set_index("date").reindex(pd.DatetimeIndex(sorted(cal_set)))
        vol = g["volume"].to_numpy()
        is_zero = np.where(np.nan_to_num(vol, nan=-1.0) == 0.0)[0]
        if len(is_zero) == 0:
            continue
        # find runs of consecutive calendar positions
        breaks = np.where(np.diff(is_zero) != 1)[0]
        runs = np.split(is_zero, breaks + 1)
        for run in runs:
            if len(run) >= ZERO_VOLUME_STRETCH_DAYS:
                d0 = pd.DatetimeIndex(calendar)[run[0]].date().isoformat()
                problems.append(f"{t}: {len(run)} zero-volume days from {d0}")
    if problems:
        raise DataQualityError(
            "zero-volume stretches on exchange-open days: "
            + "; ".join(problems[:10])
        )

    n_single_zero = 0
    for _, grp in prices.groupby("ticker"):
        n_single_zero += int((grp["volume"] == 0).sum())
    log(f"[prices] gates passed: {len(prices)} rows, {prices['ticker'].nunique()} tickers, "
        f"{len(calendar)} calendar days, {n_single_zero} isolated zero-volume days (kept, logged)")
    return prices


def load_or_download_prices(
    cache_path: str | Path,
    tickers: list[str] | None = None,
    force_download: bool = False,
    log=print,
) -> pd.DataFrame:
    """Load the parquet cache, or download + validate + cache it."""
    cache_path = Path(cache_path)
    if cache_path.exists() and not force_download:
        log(f"[prices] loading cache {cache_path}")
        prices = pd.read_parquet(cache_path)
        prices["date"] = pd.to_datetime(prices["date"])
        return validate_prices(prices, log=log)
    prices, gaps = download_prices(tickers=tickers, log=log)
    validate_prices(prices, log=log)
    cache_path.parent.mkdir(parents=True, exist_ok=True)
    prices.to_parquet(cache_path, index=False)
    log(f"[prices] cached {len(prices)} rows -> {cache_path}")
    if len(gaps):
        gaps_path = cache_path.with_name("vol_price_gaps.csv")
        gaps.to_csv(gaps_path, index=False)
        log(f"[prices] gap log -> {gaps_path}")
    return prices
